---
# Example inventory configuration for the nuclabs.dyninv.restapi plugin
# Save this file as inventory.restapi.yml

plugin: nuclabs.dyninv.restapi
url: http://api.example.com/servers

# Optional: Authentication method (none or bearer)
# auth_method: none

# For bearer token authentication:
# auth_method: bearer
# bearer_token: "your-bearer-token-here"

# Optional: Request timeout in seconds (default: 30)
# timeout: 30

# Optional: SSL certificate verification (default: true)
# validate_certs: true

# Optional: Custom CA certificate path
# ca_cert: /path/to/ca-bundle.crt

# Optional: Additional HTTP headers
# headers:
#   X-Custom-Header: "custom-value"

# Optional: Enable caching
# cache: true
# cache_plugin: ansible.builtin.jsonfile
# cache_timeout: 3600
# cache_connection: /tmp/restapi_inventory_cache

# Optional: Constructed features for dynamic groups
# keyed_groups:
#   - key: environment
#     prefix: env
#   - key: datacenter
#     separator: ""
# groups:
#   production: environment == 'prod'
# compose:
#   ansible_host: ip_address
